In [4]:
import numpy as np

In [8]:
A=np.array(([1,2,3],[4,5,6],[7,8,9]))

In [11]:
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
B=np.array(([9,8,7],[6,5,4],[3,2,1]))

In [13]:
print(B)

[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [14]:
C=A+B
print(C)

[[10 10 10]
 [10 10 10]
 [10 10 10]]


### simple element wise multiply 

In [15]:
print(A*B)

[[ 9 16 21]
 [24 25 24]
 [21 16  9]]


### matrix multiply

In [16]:
print(A@B)

[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [17]:
A.shape

(3, 3)

In [18]:
A.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [19]:
B.T

array([[9, 6, 3],
       [8, 5, 2],
       [7, 4, 1]])

### determinant

In [20]:
np.linalg.det(A)

np.float64(0.0)

### inverse 

In [24]:
np.linalg.inv(A)

LinAlgError: Singular matrix

## error cuz of A being a singular matrix means determinant is 0 . hence no inverse . 

In [21]:
print(A*5)

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


In [22]:
print(A/2)

[[0.5 1.  1.5]
 [2.  2.5 3. ]
 [3.5 4.  4.5]]


In [23]:
print(A-1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
