In [1]:
import numpy as np

# Student Marks Analyzer

This project uses NumPy to analyze student marks.

## Objectives

- Calculate statistics
- Find highest and lowest scores
- Identify top performers
- Practice NumPy aggregation functions

In [2]:
marks = np.array([
    78,
    65,
    92,
    88,
    45,
    56,
    99,
    72,
    81,
    69
])

In [3]:
marks

array([78, 65, 92, 88, 45, 56, 99, 72, 81, 69])

In [4]:
print(marks)

[78 65 92 88 45 56 99 72 81 69]


##properties of marks

In [5]:
marks.shape

(10,)

In [6]:
marks.ndim

1

In [7]:
marks.dtype

dtype('int64')

###statistics

In [8]:
np.average(marks)

np.float64(74.5)

In [9]:
np.mean(marks)

np.float64(74.5)

In [10]:
np.max(marks)

np.int64(99)

In [11]:
np.min(marks)

np.int64(45)

In [12]:
np.std(marks)

np.float64(15.75595125658873)

In [13]:
np.sort(marks)

array([45, 56, 65, 69, 72, 78, 81, 88, 92, 99])

In [14]:
marks[marks>80]

array([92, 88, 99, 81])

In [17]:
marks[-1:-3]

array([], dtype=int64)

In [18]:
marks[-1:-3:]

array([], dtype=int64)

In [19]:
marks[-3::]

array([72, 81, 69])

In [20]:
np.sort(marks)

array([45, 56, 65, 69, 72, 78, 81, 88, 92, 99])

In [21]:
marks


array([78, 65, 92, 88, 45, 56, 99, 72, 81, 69])

In [22]:
marks=np.sort(marks)

In [23]:
marks


array([45, 56, 65, 69, 72, 78, 81, 88, 92, 99])

In [24]:
marks[-3::]

array([88, 92, 99])

In [28]:
marks[marks>=40]

array([45, 56, 65, 69, 72, 78, 81, 88, 92, 99])

In [33]:
marks[marks>80]

array([81, 88, 92, 99])

In [34]:
print(marks[marks>80])

[81 88 92 99]


In [37]:
marks>80

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [38]:
print(len.marks)

AttributeError: 'builtin_function_or_method' object has no attribute 'marks'

In [39]:
np.sum(marks[marks>40])

np.int64(745)

In [40]:
np.sum(marks>40)

np.int64(10)

In [41]:
print(len(marks[marks>40]))

10


In [43]:
marks[marks<90 and marks>60]

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()